<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-FKKILF9K" failures="2" tests="5" name="Test" time="1.229" errors="0" timestamp="2023-08-20T08:11:19 CDT">
  <testcase classname="testngPackage.SkipClass" name="test1" time="0.013"/>
  <testcase classname="testngPackage.SkipClass" name="test2" time="0.003">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="testngPackage.SkipClass" name="test3" time="0.028">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testngPackage.SkipClass.test3(SkipClass.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="testngPackage.TimeOutClass" name="test1" time="0.015"/>
  <testcase classname="testngPackage.TimeOutClass" name="test2" time="1.016">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testngPackage.TimeOutClass.test2() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testngPackage.TimeOutClass.test2() didn't finish within the time-out 1000
at java.base@17.0.7/java.lang.Thread.sleep(Native Method)
at app//testngPackage.TimeOutClass.test2(TimeOutClass.java:16)
at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testngPackage.SkipClass" name="bar" time="0.0">
    <ignored/>
  </testcase> <!-- bar -->
</testsuite> <!-- Test -->
